workspace(name = "io_bazel_rules_raze")

git_repository(
    name = "io_bazel_rules_rust",
    commit = "0d0693267ba3d338230bae204bbdbfd20da0366e",
    remote = "https://github.com/mfarrugi/rules_rust.git",
)

load("@io_bazel_rules_rust//rust:repositories.bzl", "rust_repositories")

rust_repositories()

load("//complicated_cargo_library_remote:crates.bzl", "complicated_fetch_remote_crates")

complicated_fetch_remote_crates()
