workspace(name = "io_bazel_rules_raze")

git_repository(
    name = "io_bazel_rules_rust",
    commit = "5b94fdb",
    remote = "https://github.com/acmcarther/rules_rust.git",
)

load("@io_bazel_rules_rust//rust:repositories.bzl", "rust_repositories")

rust_repositories()
