workspace(name = "io_bazel_rules_raze")

git_repository(
    name = "io_bazel_rules_rust",
    commit = "df95c3e3cd5afd87a69fa71dc9a56a0d0baa7823",
    remote = "https://github.com/bazelbuild/rules_rust.git",
)

load("@io_bazel_rules_rust//rust:repositories.bzl", "rust_repositories")

rust_repositories()

load("//complicated_cargo_library_remote:crates.bzl", "complicated_fetch_remote_crates")

complicated_fetch_remote_crates()
